### get ongoing anime

GET http://localhost:8000
Accept : application/json


### get ongoing anime with pagination success

GET http://localhost:8000?pagination=2
Accept : application/json


### get ongoing anime with pagination failed instead of numbers 

GET http://localhost:8000?pagination=test
Accept : application/json

### get ongoing anime with pagination failed notfound 

GET http://localhost:8000?pagination=1
Accept : application/json

### search anime

GET http://localhost:8000/search?q=one+piece
Accept : application/json

### get anime completed 

GET http://localhost:8000/completed
Accept : application/json

### get genres 

GET http://localhost:8000/genres
Accept : application/json

### get detail

GET http://localhost:8000/detail?id=1piece-sub-indo
Accept : application/json

### get anime by genre response success

GET http://localhost:8000/genre?name=action
Accept : application/json

### get anime by genre and page response failed not found 

GET http://localhost:8000/genre?name=action&page=1
Accept: application/json