### get ongoing anime

GET http://localhost:8000
Accept : application/json


### get ongoing anime with pagination success

GET http://localhost:8000?pagination=2
Accept : application/json


### get ongoing anime with pagination failed instead of numbers 

GET http://localhost:8000?pagination=test
Accept : application/json

### get ongoing anime with pagination failed notfound 

GET http://localhost:8000?pagination=1
Accept : application/json

### search anime

GET http://localhost:8000/search?q=one+piece
Accept : application/json
